version: "3.7"
services:
  springweb:
    container_name: api-clinica-odontologica
    build: .
    ports:
      - "8081:8080"
    networks:
      - servers
    depends_on:
      - mysql_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/db_clinica_odontologica?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false

  mysql_db:
    image: "mysql:8.0"
    container_name: mysqlserver
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: alterar
      MYSQL_USER: clinica-persist
      MYSQL_ROOT_PASSWORD: 4dm1nWertvs/
    volumes:
      - db_mysql:/var/lib/mysql
    networks:
      - servers

volumes:
  db_mysql:

networks:
  servers:
    driver: bridge